"""Application-wide configuration for WealthWise."""

# --- Classification thresholds ---
FUZZY_THRESHOLD = 80
ML_CONFIDENCE_THRESHOLD = 0.75
ML_MIN_TRAINING_SAMPLES = 10


# --- Categories ---
CATEGORY_UNCATEGORIZED = "UNCATEGORIZED"
CATEGORY_INTERNAL_TRANSFER = "INTERNAL TRANSFER"
CATEGORY_FRIENDS_PAYMENTS = "FRIENDS PAYMENTS"

CATEGORIES = [
    "CANTEEN FOOD", "FOOD", "FOOD DELIVERY", "GROCERIES DELIVERY",
    "TRANSPORT", "CAB BOOKING", CATEGORY_FRIENDS_PAYMENTS, "SPORTS & ACTIVITIES",
    "PERSONAL CARE", "ONLINE SHOPPING", "GIFTS", "INVESTMENTS",
    "ENTERTAINMENT", "EDUCATION", "RAILWAY BOOKING", "BUS BOOKING",
    "TRAVEL BOOKING", "FITNESS", "BEAUTY", "OTHER"
]


# --- Rules configuration ---
RULES_FILE = "user_rules.json"
DEFAULT_RULES = "seeds_rules.json"

# --- Reimbursement logic ---
REIMBURSEMENT_WINDOW_DAYS = 7
REIMBURSEMENT_AMOUNT_TOLERANCE = 1

# --- AI model configuration ---
EMBEDDING_MODEL = "all-MiniLM-L6-v2"
GROQ_MODEL = "llama-3.3-70b-versatile"
VECTOR_DB_PATH = "./chroma_db"
TRANSACTION_COLLECTION = "transactions"
KNOWLEDGE_COLLECTION = "finance_knowledge"
